'use client'
import './globals.css'
import { useContext } from 'react';
import { Inter } from 'next/font/google'
import { DarkModeProvider, IsDarkModeContext } from './dark_mode_context'


const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create github page',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
 
  
  return (
<DarkModeProvider>
    
        <RootChild>
          {children}
        </RootChild>
      

    </DarkModeProvider>
    
  )
}

export function RootChild({
  children,
}: {
  children: React.ReactNode
}) {
  const darkModeContext = useContext(IsDarkModeContext)
  var darkMode = darkModeContext.enabled
  console.log("calling root: is  dm " + darkMode )
  var modeType : string = darkMode ? 'dark': 'light'
  const htmlClass = darkMode ? "dark" : ""
  
  const bodyClassName = 'bg-neutral-100 dark:bg-neutral-900 ' + inter.className
return (


      <html lang="th" className={htmlClass}>

        <body className={bodyClassName}>
          <div className='bg-neutral-100 dark:bg-neutral-900'>
            {children}
          </div>
        </body>
    </html>

);
}
