'use client'
import createTheme from '@mui/material/styles/createTheme'
import './globals.css'
import { useContext } from 'react';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { DarkModeProvider, IsDarkModeContext } from './dark_mode_context'
import { CssBaseline, PaletteMode, StyledEngineProvider, ThemeProvider } from '@mui/material';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create github page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
 
  
  return (
<DarkModeProvider>
    
        <RootChild>
          {children}
        </RootChild>
      

    </DarkModeProvider>
    
  )
}

export function RootChild({
  children,
}: {
  children: React.ReactNode
}) {
  const darkModeContext = useContext(IsDarkModeContext)
  var darkMode = darkModeContext.enabled
  console.log("calling root: is  dm " + darkMode )
  var modeType : PaletteMode = darkMode ? 'dark': 'light'
  var darkTheme = createTheme({
    palette: {
      mode: modeType,
    },
  });
  const htmlClass = darkMode ? "dark" : ""
  
return (
  <StyledEngineProvider injectFirst>
    <ThemeProvider theme={darkTheme} >
      <html lang="th" className={htmlClass}>
        <CssBaseline />
        <body className={inter.className}>
          <div className='bg-neutral-100 dark:bg-neutral-900'>
            {children}
          </div>
        </body>
    </html>
   </ThemeProvider>
 </StyledEngineProvider>
);
}
